export const productos = [
    {
        id: 1,
        nombre: "212",
        categoria: "Fragancias",
        sexo: "Masculino",
        marca: "Carolina Herrera",
        precio: 15000,
        stock: 20,
        descripcion: "Fragancia amaderada",
        imagen: " ",
    },
    {
        id: 2,
        nombre: "Millon",
        categoria: "Fragancias",
        sexo: "Masculino",
        marca: "Paco Rabanne",
        precio: 19000,
        stock: 29,
        descripcion: "Fragancia dulce",
        imagen: " ",
    },
    {
        id: 3,
        nombre: "212",
        categoria: "Fragancias",
        sexo: "Femenino",
        marca: "Carolina Herrera",
        precio: 50000,
        stock: 5,
        descripcion: "Fragancia amaderada con toque citrico",
        imagen: " ",
    },
    {
        id: 4,
        nombre: "CK 12",
        categoria: "Fragancias",
        sexo: "Unisex",
        marca: "Carolina Herrera",
        precio: 35000,
        stock: 3,
        descripcion: "Fragancia frutal con toque citrico",
        imagen: " ",
    },
];

