export const productos = [
    {
        id: 1,
        nombre: "212 ",
        categoria: "Fragancias",
        sexo: "Masculino",
        marca: "Carolina Herrera",
        precio: 15000,
        stock: 20,
        descripcion: "Fragancia amaderada",
        imagen: "bharara.png",
    },
    {
        id: 2,
        nombre: "Fotoprotector",
        categoria: "Solares",
        sexo: "Unisex",
        marca: "Isdin",
        precio: 5000,
        stock: 33,
        descripcion: "Solar factor 50",
        imagen: "isdinfotoprotector.png ",
    },
    {
        id: 3,
        nombre: "Lifactiv",
        categoria: "Cremas",
        sexo: "Unisex",
        marca: "Vichy",
        precio: 5000,
        stock: 3,
        descripcion: "Crema para rostro",
        imagen: "vichylidtactiv.jpeg ",
    },
    {
        id: 4,
        nombre: "Millon",
        categoria: "Fragancias",
        sexo: "Masculino",
        marca: "Paco Rabanne",
        precio: 19000,
        stock: 29,
        descripcion: "Fragancia dulce",
        imagen: "colorsmanblack.jpg ",
    },
    
    {
        id: 5,
        nombre: "CK 12",
        categoria: "Fragancias",
        sexo: "Unisex",
        marca: "Carolina Herrera",
        precio: 35000,
        stock: 3,
        descripcion: "Fragancia frutal con toque citrico",
        imagen: "philos.jpg ",
    },
    {
        id: 6,
        nombre: "212",
        categoria: "Fragancias",
        sexo: "Femenino",
        marca: "Carolina Herrera",
        precio: 50000,
        stock: 5,
        descripcion: "Fragancia amaderada con toque citrico",
        imagen: "clubnuit.png ",
    },  
    
    {
        id: 7,
        nombre: "Nebras",
        categoria: "Fragancias",
        sexo: "Femenino",
        marca: "Arabe",
        precio: 60000,
        stock: 5,
        descripcion: "Fragancia amaderada con toque citrico",
        imagen: "nebras.png ",
    },       
    {
        id: 8,
        nombre: "Vichy 50",
        categoria: "Solares",
        sexo: "Unisex",
        marca: "Vichy",
        precio: 5000,
        stock: 33,
        descripcion: "Solar factor 50",
        imagen: "vichy50.png ",
    },  
    {
        id: 9,
        nombre: "Vichy 30",
        categoria: "Solares",
        sexo: "Unisex",
        marca: "Vichy",
        precio: 5000,
        stock: 33,
        descripcion: "Solar factor 30",
        imagen: "vichy30.png ",
    },  
    
];

